[package]
name = "sprity"
version = "0.1.0"
edition = "2021"

[dependencies]
sprity-macros = { path = "./sprity-macros" }
sprity-core = { path = "./sprity-core" }

[workspace]
members = [
    "sprity-macros",
    "sprity-core",
]
