[package]
name = "sprity"
version = "0.1.0"
edition = "2021"
resolver = "2"
authors = ["Michael P. Jung <michael.jung@terreon.de>"]
description = "Sprite sheet loader"
keywords = ["sprite", "aseprite", "bevy"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/bikeshedder/sprity"
readme = "README.md"

[features]
default = ['aseprite']
aseprite = ['sprity-aseprite']

[dependencies]
sprity-aseprite = { path = "./sprity-aseprite", version = "0.1.0", optional = true }

[workspace]
members = ["sprity-*"]
