[package]
name = "sprity-codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
heck = "0.4"
itertools = "0.11"
proc-macro2 = "1"
proc-macro-error = "1"
sprity-core = { path = "../sprity-core" }
syn = "2"
thiserror = "1"
quote = "1"
