[package]
name = "sprity-codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
heck = "0.4.0"
itertools = "0.10.3"
proc-macro2 = "1.0"
proc-macro-error = "1.0.4"
sprity-core = { path = "../sprity-core" }
syn = "1.0.86"
thiserror = "1.0"
quote = "1.0.15"
