[package]
name = "sprity-aseprite"
version = "0.1.0"
edition = "2021"

[dependencies]
aseprite-reader = { git = "https://github.com/mdenchev/aseprite-reader" }
bitflags = "1.3.2"
flate2 = "1.0.22"
heck = "0.4.0"
nom = "7.1.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
strum = "0.24.0"
strum_macros = "0.24.0"
