[package]
name = "sprity-aseprite"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3.2"
heck = "0.4.0"
image = "0.24.1"
itertools = "0.10.3"
nom = "7.1.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
sprity-core = { path = "../sprity-core" }
strum = "0.24.0"
strum_macros = "0.24.0"

[[bin]]
name = "sprity-aseprite"
path = "src/main.rs"
