[package]
name = "sprity-bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bevy = "0.11"
sprity-aseprite = { path = "../sprity-aseprite" }
sprity-core = { path = "../sprity-core" }
rectangle-pack = "0.4"
