[package]
name = "sprity-bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bevy = "0.6"
sprity-aseprite = { path = "../sprity-aseprite" }
sprity-core = { path = "../sprity-core" }
rectangle-pack = "0.4.2"
