[package]
name = "sprity-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.5", features = ["derive"] }
sprity-aseprite = { path = "../sprity-aseprite" }
sprity-codegen = { path = "../sprity-codegen" }
sprity-core = { path = "../sprity-core" }
